#! /usr/bin/env python

import numpy as np
from sys import path
path.append('./moduls/')

import sys

if sys.version_info[0]>2:
    from tkinter import *
else:
    from Tkinter import *

from frmclasses import *


root = Tk()

main_frm = Frame(root,width=600)

logo_img = PhotoImage(file = './docs/logo.gif')
img_label = Label(main_frm,image=logo_img)
img_label.grid(row=0,column=0,columnspan=2)

input_obj = input_frames(main_frm)

input_obj.default_input()

input_obj.simulation_opts()
input_obj.field_frames()
input_obj.particles_frames()
#input_obj.diagnostics()

go = input_obj.get_params

read_buttom = Button(main_frm,text='read input',command=lambda : readinput(input_obj,main_frm))
read_buttom.grid(row=1,column=0)

main_frm.grid(ipadx=3,ipady=3,padx=3,pady=3)

root.title("Ewok's GUI launcher. let the force be with u")
root.mainloop()
